### ISSUE TITLE
Deprecated feature usage

### ISSUE THREAD

**Issue by tilda** [danillouz/now-syntax#1]
I now get this when using the syntax theme:
![](https://oh-no-its.theworstme.me/700e4b.png)

**Comment by danillouz** [comment]
Hi, I switched to VSCode a while back, so I haven't maintained this package at all :) I'll do my best to make some time to look into it, but feel free to send a pull request.

**Comment by tilda** [comment]
I see. Will try to get one in. Thanks

**Comment by Priultimus** [comment]
Judging that this was made back in 2017, I'm guessing there'll be no fix. That sucks, I really liked this syntax for Atom. It actually kept me from switching back to VSCode.

**Comment by getreu** [comment]
solved with pull request #2

**Comment by danillouz** [comment]
Version `0.3.0` has been released. Thank you @getreu for the PR!
